name: Record AKS Upgrade to GitHub Pages

on:
  workflow_run:
    workflows: ["Update Single AKS Cluster"]
    types:
      - completed

jobs:
  record-upgrade:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download workflow run artifacts
        uses: actions/github-script@v7
        with:
          script: |
            const run_id = process.env.GITHUB_RUN_ID || process.env.GITHUB_RUN_NUMBER;
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id
            });
            for (const artifact of artifacts.data.artifacts) {
              if (artifact.name === 'aks-upgrade-metadata') {
                await github.rest.actions.downloadArtifact({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  artifact_id: artifact.id,
                  archive_format: 'zip'
                });
              }
            }
      - name: Unzip artifact
        run: |
          mkdir -p metadata
          unzip -o aks-upgrade-metadata.zip -d metadata
      - name: Record Update in GitHub Pages
        run: |
          mkdir -p gh-pages
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          RG=$(cat metadata/resource_group)
          CLUSTER=$(cat metadata/cluster_name)
          VERSION=$(cat metadata/kubernetes_version)
          STATUS=$(cat metadata/status)
          echo "| $TIMESTAMP | $RG | $CLUSTER | $VERSION | $STATUS |" >> gh-pages/aks-updates.md
          if [ ! -f gh-pages/aks-updates.md.header ]; then
            echo "| Timestamp (UTC) | Resource Group | Cluster Name | Kubernetes Version | Status |" > gh-pages/aks-updates.md.header
            echo "|---|---|---|---|---|" >> gh-pages/aks-updates.md.header
          fi
          cat gh-pages/aks-updates.md.header gh-pages/aks-updates.md > gh-pages/aks-updates-full.md
        shell: bash
      - name: Publish Update Log to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
          publish_branch: gh-pages
          keep_files: true
          destination_dir: .
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
          commit_message: "Update AKS upgrade log [skip ci]"
