name: Update AKS Clusters

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 0' # Every Sunday at 2 AM UTC

jobs:
  update-aks:
    runs-on: ubuntu-latest
    env:
      CLUSTERS: "resourceGroup1:clusterName1,resourceGroup2:clusterName2" # Edit this line
      AKS_VERSION: "" # Set to specific version or leave empty for latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Update AKS Clusters
        run: |
          IFS=',' read -ra CLUSTER_LIST <<< "$CLUSTERS"
          for entry in "${CLUSTER_LIST[@]}"; do
            IFS=':' read -ra PARTS <<< "$entry"
            RG="${PARTS[0]}"
            CLUSTER="${PARTS[1]}"
            TARGET_K8S_VERSION=""

            if [ -z "$AKS_VERSION" ]; then
              echo "No specific version provided for $CLUSTER, querying for latest available non-preview upgrade..."
              LATEST_UPGRADE_VERSION=$(az aks get-upgrades --resource-group "$RG" --name "$CLUSTER" --query "controlPlaneProfile.upgrades[?isPreview==null].kubernetesVersion | sort(@) | [-1]" -o tsv)

              if [ -z "$LATEST_UPGRADE_VERSION" ] || [ "$LATEST_UPGRADE_VERSION" = "null" ]; then
                echo "No available non-preview upgrades found for $CLUSTER. Skipping."
                continue
              else
                echo "Latest available non-preview upgrade version for $CLUSTER: $LATEST_UPGRADE_VERSION"
                TARGET_K8S_VERSION="$LATEST_UPGRADE_VERSION"
              fi
            else
              echo "Specific version provided for all clusters: $AKS_VERSION"
              TARGET_K8S_VERSION="$AKS_VERSION"
            fi

            CURRENT_VERSION=$(az aks show --resource-group "$RG" --name "$CLUSTER" --query "kubernetesVersion" -o tsv)
            if [ "$TARGET_K8S_VERSION" = "$CURRENT_VERSION" ]; then
              echo "Cluster $CLUSTER is already at the target version $TARGET_K8S_VERSION. No upgrade needed."
            else
              echo "Attempting to upgrade $CLUSTER in $RG to version $TARGET_K8S_VERSION"
              az aks upgrade --resource-group "$RG" --name "$CLUSTER" --kubernetes-version "$TARGET_K8S_VERSION" --yes
            fi
          done
        shell: bash
